### ISSUE TITLE
Support for react native version 0.66.1

### ISSUE THREAD

**Issue by parth-91** [yz1311/react-native-wheel-picker#44]
I tried to install the dependencies on my project but I get issue of version conflicts with "react native" and "@gorhom/bottom-sheet". My package.json dependency are,

> "@apollo/client": "^3.3.20",
    "@gorhom/bottom-sheet": "^4.1.3",
    "@gregfrench/react-native-wheel-picker": "^1.2.18",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/messaging": "^12.1.0",
    "@react-native-picker/picker": "^2.2.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/core": "^6.1.0",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@sentry/react-native": "^2.6.0",
    "indicative": "^7.4.4",
    "intl": "^1.2.5",
    "jwt-decode": "^3.1.2",
    "lint-staged": "^11.2.6",
    "metro-config": "^0.66.2",
    "moment": "^2.29.1",
    "react": "^17.0.2",
    "react-intl": "^5.20.4",
    "react-native": "^0.66.1",
    "react-native-appearance": "^0.3.4",
    "react-native-config": "^1.4.2",
    "react-native-elements": "^3.4.1",
    "react-native-event-listeners": "^1.0.7",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-keychain": "^7.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-markdown-display": "^6.1.6",
    "react-native-pager-view": "^5.2.1",
    "react-native-progress": "^4.1.2",
    "react-native-radio-buttons-group": "^2.2.5",
    "react-native-reanimated": "^2.2.3",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-segmented-picker": "^2.0.2",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "^3.0.1",
    "react-native-toast-message": "^1.4.9",
    "react-native-vector-icons": "^8.1.0",
    "react-native-version-number": "^0.3.6",
    "victory-native": "^33.0.0"

I get below errors,

> npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.1
npm ERR! Found: react-native@0.66.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.66.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.4" from @yz1311/react-native-wheel-picker@0.3.9
npm ERR! node_modules/@yz1311/react-native-wheel-picker
npm ERR!   @yz1311/react-native-wheel-picker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by yz1311** [comment]
try unintall "@gregfrench/react-native-wheel-picker": "^1.2.18" and retry

**Comment by parth-91** [comment]
> try unintall "@gregfrench/react-native-wheel-picker": "^1.2.18" and retry

I tired again after uninstalling "@gregfrench/react-native-wheel-picker". Still have similar issue.

**Comment by yz1311** [comment]
I do no think it caused by my package.You can uninstall my package(if existed) to see if the error is still exist.
There is no affiliation between @gorhom/bottom-sheet and @yz1311/react-native-wheel-picker

**Comment by parth-91** [comment]
When I tried to install this dependency then only I am getting this error.

I tried to install this package using below command,
`npm i @yz1311/react-native-wheel-picker  moment react-native-modal --save --legacy-peer-deps`

I am able to install the package and its working for iOS but for android application is crashing. 

I feel this issue is because of react-native version I am using is higher then your package. Can you please look into this?

**Comment by yz1311** [comment]
> When I tried to install this dependency then only I am getting this error.
> 
> I tried to install this package using below command, `npm i @yz1311/react-native-wheel-picker moment react-native-modal --save --legacy-peer-deps`
> 
> I am able to install the package and its working for iOS but for android application is crashing.
> 
> I feel this issue is because of react-native version I am using is higher then your package. Can you please look into this?

I use react native 0.66.3, there is no problem. Can you use android studio's  logcat to locate the errors?Then i can figure it out.

**Comment by parth-91** [comment]
I tried it using android studio and I get below errors,

> 2021-11-18 15:06:03.304 15008-15072/com.test.mobile E/unknown:NativeModuleInitError: Failed to create NativeModule "UIManager"
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aigestudio/wheelpicker/view/WheelCurvedPicker;
        at com.zyu.ReactNativeWheelPickerPackage.createViewManagers(ReactNativeWheelPickerPackage.java:28)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:889)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:175)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:176)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:143)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.aigestudio.wheelpicker.view.WheelCurvedPicker" on path: DexPathList[[zip file "/data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/lib/arm, /data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zyu.ReactNativeWheelPickerPackage.createViewManagers(ReactNativeWheelPickerPackage.java:28) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:889) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:175) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469) 
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:176) 
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:143) 
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100) 
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065) 
        at java.lang.Thread.run(Thread.java:764) 
2021-11-18 15:06:03.308 15008-15072/com.test.mobile E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.test.mobile, PID: 15008
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aigestudio/wheelpicker/view/WheelCurvedPicker;
        at com.zyu.ReactNativeWheelPickerPackage.createViewManagers(ReactNativeWheelPickerPackage.java:28)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:889)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:175)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:176)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:143)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.aigestudio.wheelpicker.view.WheelCurvedPicker" on path: DexPathList[[zip file "/data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/lib/arm, /data/app/com.test.mobile-3UFLLxomD9ZA28-5ePxJ_w==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zyu.ReactNativeWheelPickerPackage.createViewManagers(ReactNativeWheelPickerPackage.java:28) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:889) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:175) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469) 
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:176) 
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:143) 
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100) 
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1336) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by yz1311** [comment]
Your project do not download the android native library 'com.aigestudio.wheelpicker'
Normally in the android studio project panel,
the project section should include :
![image](https://user-images.githubusercontent.com/9854019/142393779-3a107b98-7912-4fe9-825c-850491d17667.png)
and the 'External Libraries' should include: 
![image](https://user-images.githubusercontent.com/9854019/142394011-9b77e9b7-fc04-426e-b552-65669ac5ac52.png)
